chore: Validate with ruff
Zextras/carbonio-preview-ce pull request #46
Opened 2023-07-17 08:43 UTC by RakuJa

# Description

Implement ruff code guidelines

## Type of change

Please delete options that are not relevant or put an 'x' on the desired options.

- [x] New feature (non-breaking change which adds functionality)
# Checklist:

This checklist is used as a reminder to avoid half-baked code
- [x] The PR title follows the following structure:" type[optional scope]: PREV-XX - LONG DESCRIPTION "
- [x] I have bumped both the PKGBUILD version and controller version, and they are the same.
- [x] I have correctly installed and enabled pre-commit
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] If I have introduced new dependencies I have added them to the pre-commit unittest additional_dependencies AND to the THIRDPARTIES file

2023-07-25 14:44 UTC, federicorispo requested changes
After a quick grep I found these hardcoded status codes. I already commented some of them during the review but I am not sure if the proposed solutions are working or not:

```
app/core/services/document_service.py:55:                        response_data.value_or(RequestResp(status_code=200)).content,
app/core/services/document_service.py:127:                        response_data.value_or(RequestResp(status_code=200)).content,
app/core/services/image_service.py:148:                    response_data.value_or(RequestResp(status_code=200)).content,
app/core/services/pdf_service.py:53:                    response_data.value_or(RequestResp(status_code=200)).content,
app/core/services/pdf_service.py:122:                        response_data.value_or(RequestResp(status_code=200)).content,

app/core/resources/data_validator.py:116:            status_code=422,
app/core/services/document_manipulation/document_manipulation.py:164:        raise HTTPException(status_code=400, detail="Invalid pdf file") from e
app/core/services/image_service.py:62:        raise HTTPException(status_code=400, detail=str(e)) from None
app/core/services/image_service.py:93:        raise HTTPException(status_code=400, detail=str(e)) from None
app/core/services/image_service.py:108:        raise HTTPException(status_code=400, detail=str(e)) from None
app/core/services/image_service.py:123:        raise HTTPException(status_code=400, detail=str(e)) from e
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/resources/data_validator.py
> +            status_code=422,
```suggestion
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/routers/document.py
> +    responses={400: {"description": message.INPUT_ERROR}},
```suggestion
    responses={status.HTTP_400_BAD_REQUEST: {"description": message.INPUT_ERROR}},
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/routers/document.py
> +    responses={400: {"description": message.INPUT_ERROR}},
See also row 167

2023-07-25 14:44 UTC, federicorispo commented on app/core/routers/pdf.py
> +    responses={400: {"description": message.INPUT_ERROR}},
```suggestion
    responses={status.HTTP_400_BAD_REQUEST: {"description": message.INPUT_ERROR}},
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/document_manipulation/document_manipulation.py
> +        raise HTTPException(status_code=400, detail="Invalid pdf file") from e
```suggestion
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid pdf file") from e
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/document_service.py
> +                        response_data.value_or(RequestResp(status_code=200)).content,
```suggestion
                        response_data.value_or(RequestResp(status_code=status.HTTP_200_OK)).content,
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/document_service.py
> +                        response_data.value_or(RequestResp(status_code=200)).content,
```suggestion
                        response_data.value_or(RequestResp(status_code=status.HTTP_200_OK)).content,
```

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/image_manipulation/gif_utility_functions.py
> +    raise ValueError(msg)
What is the benefit of the `msg` variable?

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/image_manipulation/gif_utility_functions.py
> +    draw.ellipse((0, 0, *size), fill=0)
Why this change? I notice that the [#ellipse](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.ellipse) method wants a sequence of two values

2023-07-25 14:44 UTC, federicorispo commented on app/core/services/image_service.py
> +        raise HTTPException(status_code=400, detail=str(e)) from None
```suggestion
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e)) from None
```

2023-07-26 07:32 UTC, RakuJa commented on app/core/services/image_manipulation/gif_utility_functions.py
> +    draw.ellipse((0, 0, *size), fill=0)
(0,0) + size is a tuple concatenation, not a sum of first value of the tuple + first value of the second tuple and so on. => (0,0, size.x, size.y)
So, using the unpacking operator (*) is a little bit more explicit and suggested by default.
(0,0, *size) => (0,0, size.x, size.y)

2023-07-26 07:37 UTC, RakuJa commented on app/core/services/image_manipulation/gif_utility_functions.py
> +    raise ValueError(msg)
https://beta.ruff.rs/docs/rules/raw-string-in-exception/

2023-07-26 08:55 UTC, federicorispo approved these changes

2023-07-26 08:58 UTC, merged